language: scala
scala:
  - 2.10.6
  - 2.11.8
jdk:
  - oraclejdk7
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalastyle test:scalastyle coverage test coverageReport coverageAggregate docs/makeSite
before_install:
  - pip install --user codecov
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/052fbe6b65251b86f242
    on_success: change
    on_failure: always
    on_start: never
